### ISSUE TITLE
请教下javplayer的模型训练

### ISSUE THREAD

**Issue by siqwew** [FrankLinxzx/FrankLinxzx.github.io#1]
请问你是中国人吗，我想请教一下你训练的模型比原版好吗

**Comment by FrankLinxzx** [comment]
> 请问你是中国人吗，我想请教一下你训练的模型比原版好吗

還未知   訓練中   loss 還沒壓到很低

**Comment by siqwew** [comment]
最近流出很多，拿来训练估计效果不错，我也想弄训练，但是我不怎么会
